EMAIL_ADDRESS=mintybank09@gmail.com
EMAIL_PASSWORD=lovitlkfdoqfctfm
OPENAI_API_KEY= sk-0rYpX1J3BlbkFJHHW4vY2Vt9zQ9P6F6zT3BlbkFJHHW4vY2Vt9zQ9P6F6z3BlbkFJHH
GEMINI_API_KEY=AIzaSyCdAZk_IBmCU67QY2b8bDgpCncr2ddtfEY